[build]
publish = "public"
command = "hugo"

[context.production.environment]
# Must be removed once we merge.
HUGO_BASEURL = "https://k8sio-hugo-migration.netlify.com/"
HUGO_VERSION = "0.40.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.40.2"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.40.2"

